services:
    app:
        build: .
        ports:
            - "80:8000"
        environment:
            APP_ENV: production
            APP_DEBUG: false
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: password
            REDIS_CLIENT: phpredis
            REDIS_HOST: redis
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
            REDIS_DB: 0
            REDIS_CACHE_DB: 1
        depends_on:
            - db
            - redis

    db:
        image: postgres:17
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - psql_data:/var/lib/postgresql/data
        ports:
            - '${DB_PORT}:5432'
        healthcheck:
#            test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME} -d $${DB_DATABASE} -h localhost"]
            test: ["CMD-SHELL", "pg_isready -U laravel -d laravel"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    psql_data:
    redis_data:
